# Generated by Django 5.2.11 on 2026-03-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("celery_monitor", "0001_create_status_counts_materialized_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="CeleryStatusCount",
            fields=[
                (
                    "status",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("count", models.IntegerField()),
            ],
            options={
                "db_table": "celery_status_counts",
                "managed": False,
            },
        ),
    ]
