# Generated by Django 6.0.2 on 2026-09-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("celery_monitor", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CeleryMonitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "celery monitor",
                "permissions": (
                    ("view_celery_monitor", "Can view Celery Monitor"),
                    ("manage_celery_monitor", "Can manage Celery tasks and queues"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
